#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivercarro(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
mod="Mod4"
alt="Mod1"

## DEBUG
# Reload river configuration
riverctl map normal $mod+Shift R spawn "$HOME/.config/river/init"

#Super+P open wofi
riverctl map normal $mod P spawn "wofi"

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod+Shift Return spawn foot

# Super+Q to close the focused view
riverctl map normal $mod Q close

# Super+Shift+E to exit river
riverctl map normal $mod+Shift E exit

# Control+ALt+Supr exit menu
riverctl map normal Control+$alt BackSpace spawn 'wlogout -b 4 -p layer-shell'

# Control+ALt+L to lock screen
riverctl map normal Control+$alt L spawn sway-lock

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivercarro(1)
riverctl map normal $mod H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivercarro "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivercarro(1)
riverctl map normal $mod+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivercarro "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal $mod+$alt H move left 100
riverctl map normal $mod+$alt J move down 100
riverctl map normal $mod+$alt K move up 100
riverctl map normal $mod+$alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+$alt+Control H snap left
riverctl map normal $mod+$alt+Control J snap down
riverctl map normal $mod+$alt+Control K snap up
riverctl map normal $mod+$alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal $mod+$alt+Shift H resize horizontal -100
riverctl map normal $mod+$alt+Shift J resize vertical 100
riverctl map normal $mod+$alt+Shift K resize vertical -100
riverctl map normal $mod+$alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-5] to focus tag [0-4]
    riverctl map normal $mod $i set-focused-tags $tags

    # Super+Shift+[1-5] to tag focused view with tag [0-4]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-5] to toggle focus of tag [0-4]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-5] to toggle tag [0-4] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal $mod Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left"
riverctl map normal $mod M send-layout-cmd rivercarro "main-location monocle"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume 0 +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume 0 -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute 0 toggle'
    riverctl map $mode None XF86AudioMicMute      spawn 'pactl set-source-mute 0 toggle'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Take screenshots
riverctl map normal None Print spawn 'grim -g "$(slurp)"'

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl border-width 4

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set cursor behavior
riverctl focus-follows-cursor normal
riverctl xcursor-theme Breeze_Obsidian 32

# Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"

# Set the default layout generator to be rivercarro and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
riverctl spawn "killall rivercarro"
riverctl spawn "exec rivercarro -outer-gaps 10"

# Set bar
riverctl spawn "killall waybar"
riverctl spawn "exec waybar"

# Set Wallpaper
riverctl spawn "killall swaybg"
riverctl spawn "exec swaybg -i ${HOME}/Pictures/river-wallpaper"

# Start Audio
riverctl spawn "killall pipewire"
riverctl spawn "exec pipewire"
riverctl spawn "killall pipewire-pulse"
riverctl spawn "exec pipewire-pulse"

# Start bluetooth manger
riverctl spawn "exec blueman-applet"

# Start notification daemon
riverctl spawn "killall dunst"
riverctl spawn "exec dunst"

# screen sharing configuration
exec dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
